import streamlit as st
import pandas as pd
import json
import sqlite3
import time
from fastapi import FastAPI
from pydantic import BaseModel
from sqlalchemy import create_engine, Column, String, Integer, Float
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

# --- CONFIGURATION & DATABASE SETUP ---
DB_URL = "sqlite:///zombie_api.db"
Base = declarative_base()

class APIEndpoint(Base):
    __tablename__ = 'api_inventory'
    id = Column(Integer, primary_key=True)
    endpoint = Column(String)
    method = Column(String)
    traffic_count = Column(Integer)
    status = Column(String) # Active, Zombie, Shadow, Deprecated
    risk_level = Column(String) # Low, Medium, High
    risk_score = Column(Float)
    recommendation = Column(String)

engine = create_engine(DB_URL, connect_args={"check_same_thread": False})
Base.metadata.create_all(engine)
SessionLocal = sessionmaker(bind=engine)

# --- COMPONENT 1: MOCK DATA & LOGS ---
# Simulating the logs that would normally be generated by a gateway or traffic analyzer
MOCK_LOGS = {
    "/api/v1/users": 120,
    "/api/v1/payments": 95,
    "/api/v1/transactions": 80,
    "/api/v1/old-login": 0,
    "/api/v1/test-api": 0,
    "/internal/debug": 1,
    "/api/v2/auth": 200,
    "/dev/experimental": 0
}

MOCK_SPEC = [
    {"endpoint": "/api/v1/users", "method": "GET"},
    {"endpoint": "/api/v1/payments", "method": "GET"},
    {"endpoint": "/api/v1/transactions", "method": "GET"},
    {"endpoint": "/api/v1/old-login", "method": "GET"},
    {"endpoint": "/api/v1/test-api", "method": "GET"},
    {"endpoint": "/internal/debug", "method": "GET"},
    {"endpoint": "/api/v2/auth", "method": "POST"},
    {"endpoint": "/dev/experimental", "method": "GET"}
]

# --- COMPONENT 2: SCANNER & CLASSIFICATION ENGINE ---
def classify_api(endpoint, traffic):
    """
    Logic:
    - Active: traffic > 10
    - Zombie: traffic == 0 AND (old/test/experimental)
    - Shadow: internal/debug/dev in path
    - Deprecated: traffic < 10 but not zero
    """
    status = "Active"
    risk = "Low"
    score = 10.0
    rec = "No action required."

    # Classification logic
    if any(word in endpoint.lower() for word in ["internal", "debug", "dev"]):
        status = "Shadow"
        risk = "Medium"
        score = 65.0
        rec = "Restrict internal endpoint exposure; check authentication."
    elif traffic == 0 and any(word in endpoint.lower() for word in ["old", "test", "experimental"]):
        status = "Zombie"
        risk = "High"
        score = 95.0
        rec = "Candidate for decommissioning. No traffic detected on legacy endpoint."
    elif 0 < traffic < 10:
        status = "Deprecated"
        risk = "Medium"
        score = 45.0
        rec = "Low usage. Plan migration to latest API version."
    elif traffic == 0:
        status = "Inactive"
        risk = "Medium"
        score = 30.0
        rec = "Monitor for potential decommissioning."

    return status, risk, score, rec

def run_scanner():
    """Simulates scanning the OpenAPI spec and matching with logs."""
    db = SessionLocal()
    # Clear old data for fresh prototype demo
    db.query(APIEndpoint).delete()
    
    for item in MOCK_SPEC:
        traffic = MOCK_LOGS.get(item['endpoint'], 0)
        status, risk, score, rec = classify_api(item['endpoint'], traffic)
        
        new_entry = APIEndpoint(
            endpoint=item['endpoint'],
            method=item['method'],
            traffic_count=traffic,
            status=status,
            risk_level=risk,
            risk_score=score,
            recommendation=rec
        )
        db.add(new_entry)
    
    db.commit()
    db.close()

# --- COMPONENT 3: STREAMLIT DASHBOARD ---
def main():
    st.set_page_config(page_title="Zombie API Discovery", layout="wide")

    # Sidebar
    st.sidebar.title("🛡️ API Sentinel")
    st.sidebar.info("Prototype: Zombie API Discovery & Defense")
    
    if st.sidebar.button("🚀 Run API Discovery Scan"):
        with st.spinner("Scanning system endpoints and traffic logs..."):
            run_scanner()
            time.sleep(1) # Simulate network delay
            st.success("Scan Complete!")

    # Load Data
    db = SessionLocal()
    data = db.query(APIEndpoint).all()
    db.close()

    df = pd.DataFrame([{
        "Endpoint": d.endpoint,
        "Method": d.method,
        "Traffic": d.traffic_count,
        "Status": d.status,
        "Risk": d.risk_level,
        "Score": d.risk_score,
        "Recommendation": d.recommendation
    } for d in data])

    # Header
    st.title("Zombie API Discovery Dashboard")
    st.markdown("---")

    if df.empty:
        st.warning("No data found. Please run the scanner from the sidebar.")
    else:
        # Metrics Row
        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Total APIs", len(df))
        col2.metric("Zombie APIs", len(df[df['Status'] == 'Zombie']), delta_color="inverse")
        col3.metric("Shadow APIs", len(df[df['Status'] == 'Shadow']))
        col4.metric("Active APIs", len(df[df['Status'] == 'Active']))

        # Alerts Section
        high_risk = df[df['Risk'] == 'High']
        if not high_risk.empty:
            st.subheader("⚠️ Critical Security Alerts")
            for _, row in high_risk.iterrows():
                st.error(f"**{row['Status']} API Detected**: `{row['Endpoint']}`\n\n**Recommendation**: {row['Recommendation']}")

        # Visualizations
        st.markdown("---")
        vcol1, vcol2 = st.columns(2)
        
        with vcol1:
            st.subheader("API Status Distribution")
            status_counts = df['Status'].value_counts()
            st.bar_chart(status_counts)

        with vcol2:
            st.subheader("Traffic Analysis")
            st.line_chart(df.set_index('Endpoint')['Traffic'])

        # Inventory Table
        st.subheader("Full API Inventory")
        
        # Color coding logic for the dataframe
        def color_status(val):
            color = 'white'
            if val == 'Zombie': color = '#ff4b4b'
            elif val == 'Shadow': color = '#ffa500'
            elif val == 'Deprecated': color = '#ffff00'
            return f'background-color: {color}; color: black'

        st.dataframe(df.style.applymap(color_status, subset=['Status']), use_container_width=True)

        # Decommissioning Action
        st.markdown("---")
        st.subheader("Manage Lifecycle")
        target_api = st.selectbox("Select API to decommission:", df['Endpoint'].tolist())
        if st.button("Confirm Decommission"):
            st.warning(f"Protocol Initiated: Routing traffic away from {target_api} and updating firewall rules.")

# Run the app
if __name__ == "__main__":
    main()